### ISSUE TITLE
Question: is using this.form.validateAllFormFields(); needed?

### ISSUE THREAD

**Issue by tscislo** [EndyKaufman/ngx-dynamic-form-builder#174]
In your examples on stackblitz: https://stackblitz.com/edit/ngx-dynamic-form-builder-rym9yj?file=app%2Fuser-panel%2Fuser-panel.component.ts 
you're using 
this.form.validateAllFormFields();

when you load data into form is that really needed if so why?

**Comment by EndyKaufman** [comment]
![image](https://user-images.githubusercontent.com/4127109/129881378-cb148d5c-681a-4ed3-bea7-1d7129080aa8.png)
This was necessary for the validation state to be immediately activated, it was done a long time ago, now it is possible that the reason for which this feature was done has been fixed in the Angular

you can pass this option to the constructor
```
fb = new DynamicFormBuilder({ validateAllFormFields: true });
```
